notebook_metadata_filter="kernelspec,jupytext,exports,math,rise,semantic,-jupytext.text_representation.jupytext_version"
cell_metadata_filter="all,-autoscroll,-collapsed,-scrolled,-trusted,-ExecuteTime,-jp-MarkdownHeadingCollapsed"